---
title: "FFS RF"
author: "Josh Erickson"
date: "April 14, 2020"
output: html_document
---

```{r setup, include=FALSE}

library(caret)
library(CAST)
library(randomForest)
library(tidyverse)
```

#### FFS Random Forest

So with the FFS we will just use the default parameters for Random Forest (e.g. mtry = 2, 4, 6 and ntrees = 500)
```{r, eval=FALSE}


predictorsRF <- FeatureSelection[,c("twi30agg","tpi30agg","accum30","vv30agg", "vvsd30agg","npol30agg","NDVI_med", "nppmmid30agg","deficitRS","cad30RS","decid30RS","cpg30precip","Green_med","NIR_med")]

levels(FeatureSelection$stream) <- c("X0", "X1")

responseRF <- FeatureSelection$stream

```

*FFS Kmeans Random Forest with clusters*

```{r eval=FALSE}
#bring in cores
cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)


#set up control
ctrlK80 <- trainControl(method="repeatedcv",
                     repeats = 5,number = 10,
                     allowParallel = TRUE,
                     returnResamp = "all", 
                     verbose = FALSE, 
                     classProbs = TRUE,
                     summaryFunction = fourStats,
                     index = indicesKsel80$index,
                     savePredictions = 'all')
#run
set.seed(1234)
ffsK80 <- ffs(predictorsRF,responseRF, 
  metric = "ROC",
  method = "rf",
  trControl = ctrlK80)


#now remove cluster. consistency...
stopCluster(cluster)
registerDoSEQ()
```

*now with a 40 cluster LLO*

```{r eval=FALSE}
#bring in cores
cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)


#set up control
ctrlK_40 <- trainControl(method="repeatedcv",
                     repeats = 5,number = 10,
                     allowParallel = TRUE,
                     returnResamp = "all", 
                     verbose = FALSE, 
                     classProbs = TRUE,
                     summaryFunction = fourStats,
                     index = indicesKsel40$index,
                     savePredictions = 'all')
#run
set.seed(1234)
ffsK_40 <- ffs(predictorsRF,responseRF, 
  metric = "ROC",
  method = "rf",
  trControl = ctrlK_40)
ffsK_40$selectedvars
#now remove cluster. consistency...
stopCluster(cluster)
registerDoSEQ()
```



*FFS Kmeans Random Forest without spatial dependance structures*

```{r eval=FALSE}
#bring in cores
cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)


#set up control
ctrlK_noSD <- trainControl(method="repeatedcv",
                     repeats = 5,number = 10,
                     allowParallel = TRUE,
                     returnResamp = "all", 
                     verbose = FALSE, 
                     classProbs = TRUE,
                     summaryFunction = fourStats,
                     savePredictions = 'all')
#run
set.seed(1234)
ffsK_noSD <- ffs(predictorsRF,responseRF, 
  metric = "ROC",
  method = "rf",
  trControl = ctrlK_noSD)


#now remove cluster. consistency...
stopCluster(cluster)
registerDoSEQ()
```


```{r}

ffsK_LLO80$selectedvars
ffsK80$selectedvars
ffsK_noSD$selectedvars

FeatureSelection %>% count(spatial_cluster80, sort = TRUE) %>% 
  ggplot() + geom_freqpoly(aes(n, ..density..), binwidth = 5)

```

