---
title: "tuning"
author: "Josh Erickson"
date: "April 15, 2020"
output: html_document
---

```{r setup, include=FALSE}

load("D:/Rcodes/Water_Prediction/Hird_Water_Prediction/waterD/waterPred/workingThoughProject/workingthroughproj.RData")
library(sp)
library(rgdal)
library(rgeos)
library(raster)
library(automap)
library(caret)
library(CAST)
library(blockCV)
library(tidyverse)
library(gridExtra)
library(reshape2)
library(doParallel)
library(parallel)
library(mlbench)
library(plotROC)
library(pdp)
library(vip)
library(gridGraphics)
library(grid)
```

Now tune the variables from the feature selection.

### FFS tuned Random Forest

*FFS 12th HUC Random Forest Tune*
```{r, eval=FALSE}

#get variable subset from oneSD results
library(recipes)
ffs12rf.hw$selectedvars
 "accum30"   "decid30RS" "npol30agg"
levels(traintune$stream) <- c("X0","X1")

rec_tune12ffs <-   recipe(stream ~ ., data = traintune) %>% 
  update_role(-stream,-accum30,-decid30RS,-npol30agg, new_role = "bring along")


cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

set.seed(1234)
ffs12tune.hw <- train(rec_tune12ffs, data = traintune,
              method = thresh_code,
              metric = "J",
              tuneGrid = expand.grid(mtry = 2,ntree=seq(100,1500,50),
                                     threshold = seq(.01,.99,.03)),
              trControl = trainControl(method = "repeatedcv",
                                       repeats = 5,
                                       classProbs = TRUE,
                                       savePredictions = 'all',
                                       index = indices12tune$index,
                                       summaryFunction = fourStats))

stopCluster(cluster)
registerDoSEQ()

```

```{r echo=FALSE, message=FALSE, fig.align='center', fig.height=16, fig.width=13}
ffs12tune.hw$bestTune
f.res12 <- ffs12tune.hw$results %>% filter(mtry == 2 & ntree == 1350)
metrics <- f.res12[,c(3,5,6,19,20)]
metrics <- reshape2::melt(metrics, id.vars = "threshold", 
                variable.name = "Resampled",
                value.name = "Data")

g <- ggplot(metrics, aes(x = threshold, y = Data, color = Resampled)) + 
  geom_line() + 
  ylab("") + xlab("Probability Cutoff") +
  theme(legend.position = "top") + ggtitle("Balanced")

confusionMatrix.train(ffs12tune.hw,norm = "none")



```

*FFS blockCV Random Forest Tune*
```{r, eval=FALSE}

#get variable subset from oneSD results
library(recipes)
ffsMedrf.hw$selectedvars
 "accum30"      "ndwias30agg"  "nppmmid30agg" "cad30RS"     
[5] "tpi30agg"     "ndvi30yrRS"   "ndvias30agg"


rec_tuneMedffs <-   recipe(stream ~ ., data = traintune) %>% 
  update_role(-stream,-accum30,-ndwias30agg,-nppmmid30agg,-cad30RS,-tpi30agg,-ndvi30yrRS,-ndvias30agg, new_role = "bring along")


cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

set.seed(1234)
ffsMedtune.hw <- train(rec_tuneMedffs, data = traintune,
              method = thresh_code,
              metric = "J",
              tuneGrid = expand.grid(mtry = 2:6,ntree=seq(100,1500,50),
                                     threshold = seq(.01,.99,.03)),
              trControl = trainControl(method = "repeatedcv",
                                       repeats = 5,
                                       classProbs = TRUE,
                                       savePredictions = 'all',
                                       index = indicesMedtune$index,
                                       summaryFunction = fourStats))

stopCluster(cluster)
registerDoSEQ()

```

```{r echo=FALSE, message=FALSE, fig.align='center', fig.height=16, fig.width=13}
ffsMedtune.hw$bestTune
f.resMed <- ffsMedtune.hw$results %>% filter(mtry == 2 & ntree == 750)

metrics <- f.resMed[,c(3,5,6,19,20)]
metrics <- reshape2::melt(metrics, id.vars = "threshold", 
                variable.name = "Resampled",
                value.name = "Data")

g <- ggplot(metrics, aes(x = threshold, y = Data, color = Resampled)) + 
  geom_line() + 
  ylab("") + xlab("Probability Cutoff") +
  theme(legend.position = "top") + ggtitle("Balanced")

confusionMatrix(ffsMedtune.hw,norm = "none")
f.resMed
ffsMedtune.hw$bestTune

```



*FFS 14th HUC Random Forest Tune*
```{r, eval=FALSE}


library(recipes)
ffs14rf.hw$selectedvars

 [1] "accum30"      "nppmmid30agg" "cpg30precip"  "vvsd30agg"   
 [5] "B8_30agg"     "vv30agg"      "tpi30agg"     "deficitRS"   
 [9] "ndwias30agg"  "cad30RS"      "npol30agg" 

rec_tune14ffs <-   recipe(stream ~ ., data = traintune) %>% 
  update_role(-stream,-accum30,-ndwias30agg,-nppmmid30agg,-cad30RS,-tpi30agg,-ndvi30yrRS,-ndvias30agg,-cpg30precip,-vvsd30agg,-B8_30agg,-vv30agg,-deficitRS,-npol30agg, new_role = "bring along")


cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

set.seed(1234)
ffs14tune.hw <- train(rec_tune14ffs, data = traintune,
              method = thresh_code,
              metric = "J",
              tuneGrid = expand.grid(mtry = 2:10,ntree=seq(100,1500,50),
                                     threshold = seq(.01,.99,.03)),
              trControl = trainControl(method = "repeatedcv",
                                       repeats = 5,
                                       classProbs = TRUE,
                                       savePredictions = 'all',
                                       index = indices14tune$index,
                                       summaryFunction = fourStats))

stopCluster(cluster)
registerDoSEQ()

```

```{r echo=FALSE, message=FALSE, fig.align='center', fig.height=16, fig.width=13}

confusionMatrix(ffs14tune.hw,norm = "none")


f.res14 <- ffs14tune.hw$results %>% filter(mtry == 6 & ntree == 1050)


metrics <- f.res14[,c(3,5,6,19,20)]
metrics <- reshape2::melt(metrics, id.vars = "threshold", 
                variable.name = "Resampled",
                value.name = "Data")

g <- ggplot(metrics, aes(x = threshold, y = Data, color = Resampled)) + 
  geom_line() + 
  ylab("") + xlab("Probability Cutoff") +
  theme(legend.position = "top") + ggtitle("Balanced")
```

*Kmeans Random Forest Tune*
```{r, eval=FALSE}


library(recipes)
ffsKrf.hw$selectedvars

[1] "accum30"      "nppmmid30agg" "cpg30precip"  "decid30RS"   
 [5] "B2_30agg"     "ndvi30yrRS"   "ndwias30agg"  "cad30RS"     
 [9] "tpi30agg"     "vvsd30agg"    "vv30agg"      "B8_30agg"

rec_tuneKffs <-   recipe(stream ~ ., data = traintune) %>% 
  update_role(-stream,-accum30,-ndwias30agg,-nppmmid30agg,-cad30RS,-tpi30agg,-ndvi30yrRS,-cpg30precip,-vvsd30agg,-B8_30agg,-vv30agg,-decid30RS,-B2_30agg, new_role = "bring along")


cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

set.seed(1234)
ffsKtune.hw <- train(rec_tuneKffs, data = traintune,
              method = thresh_code,
              metric = "J",
              tuneGrid = expand.grid(mtry = 2:11,ntree=seq(100,1500,50),
                                     threshold = seq(.01,.99,.03)),
              trControl = trainControl(method = "repeatedcv",
                                       repeats = 5,
                                       classProbs = TRUE,
                                       savePredictions = 'all',
                                       index = indicesKtune$index,
                                       summaryFunction = fourStats))

stopCluster(cluster)
registerDoSEQ()

```

```{r echo=FALSE, message=FALSE, fig.align='center', fig.height=16, fig.width=13}

confusionMatrix(ffsKtune.hw,norm = "none")


```





