---
title: "ffs_final_results"
author: "Josh Erickson"
date: "3/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(thematic)
ggplot2::theme_set(ggplot2::theme_bw())
thematic_on(
  bg = "auto", fg = "auto", accent = "auto", font = "Indie Flower",
  sequential = sequential_gradient(), qualitative = okabe_ito()
)

```

```{r, warning=FALSE, message=F, echo=F}

all_results <- read_csv("D:/R_folder/Water_Prediction/Final_paper_water_prediction/hwstreamprediction/zach/all_results_final.csv")

ffs_best <- all_results %>% group_by(model,cluster) %>% slice_max(order_by = Accuracy)%>% ungroup()

all_models <- ffs_best %>% mutate(cluster_no = str_replace_all(cluster, '[.]', '_'),
                                    cluster_no = parse_number(cluster_no))
all_models_gbm <- all_models %>% filter(model == 'gbm')

```



```{r, echo=F}
random_cv <- read_csv("D:/R_folder/Water_Prediction/Final_paper_water_prediction/hwstreamprediction/zach/results_final_10_and_Rcv.csv")

high_gbm <- random_cv %>% filter(model == "GBM_Rcv") %>% slice_max(Accuracy) %>% mutate(cluster_no = 0, model = "gbm", model2 = "GBM_Rcv")

#should be "RF_Rcv" just named it wrong, e.g. RF_k10.
high_rf <- random_cv %>% filter(model == "RF_k10") %>% slice_max(Accuracy)%>% mutate(cluster_no = 0, model = "rf", model2 = "RF_Rcv")

topo_10 <- random_cv %>% filter(model == "Topo_k10") %>% slice_max(Accuracy)%>% mutate(cluster_no = 10, model = "topo", model2 = "Topo_k10")

topo_cv <- random_cv %>% filter(model == "Topo_Rcv") %>% slice_max(Accuracy)%>% mutate(cluster_no = 0, model = "topo", model2 = "Topo_Rcv")

k10_gbm <- random_cv %>% filter(model == "GBM_k10") %>% slice_max(Accuracy) %>% mutate(cluster_no = 10, model = "gbm", model2 = "GBM_k10")

all_models <- plyr::rbind.fill(all_models, high_gbm, high_rf, topo_10, topo_cv, k10_gbm) 
```


```{r}


trace(grDevices::png, quote({
  if (missing(type) && missing(antialias)) {
    type <- "cairo-png"
    antialias <- "subpixel"
  }
}), print = FALSE)

all_model_vars <- all_models_gbm %>% separate(char_vars, into = letters[1:15], sep = ',') %>% 
  pivot_longer(cols = 44:54) %>% mutate(value = str_remove_all(value, ' ') %>% factor(),
                                        value = fct_recode(value, NPP = 'nppmmid30agg',
                                                           UAA = 'accum30', TPI = 'tpi30agg',
                                                           Deficit = 'deficitRS', Deciduous = 'decid30RS',
                                                           CAD = 'cad30RS', TWI = 'twi30agg',
                                                           NDVI = 'NDVI_med', NPOL = 'npol30agg',
                                                           NIR = 'NIR_med', Green = 'Green_med',
                                                           `VV sd` = 'vvsd30agg', VV = 'vv30agg',
                                                           `CPG Precip` = 'cpg30precip'))
all_model_vars %>% count(value,model, sort = T) %>% na.omit() %>% mutate(value = fct_reorder(value, n)) %>% 
  ggplot(aes(value, n)) + 
   geom_col(alpha = 0.5) + 
  geom_point()  +  geom_text(aes(x = 'NIR', y = 111, label =  '75th Percentile'), size = 5) + annotate('segment', y =100.5, yend = 99, x = 'NIR', xend = 'NIR')  +
  labs(x = "Variables", y = "Count", title = "Variable Selection Counts for FFS Models") +
  coord_flip() +geom_hline(yintercept = count_quant$value[3], linetype = 3,lwd=1) + geom_text(aes(label = n), nudge_y = 3) + theme(axis.title = element_text(size = 20),
                                                                                                                                   axis.text = element_text(size = 20))



model_count <- all_model_vars %>% count(value,model, sort = T) %>% na.omit() 
count_quant <- quantile(x = model_count$n, probs = c(.25,.5,.75), na.rm = T)
count_quant <- data.frame(value = count_quant, perc = c(.25,.5,.75))
count_quant %>% ggplot(aes(perc, value)) + geom_line() + geom_vline(xintercept = 0.77)
```

